site_name: 'プログラミング言語 Mokkosu'
repo_url: https://github.com/lambdataro/Mokkosu
theme: Bootstrap
pages:
- ['index.md', 'トップ']
- ['start/install.md', '始め方', 'インストールと実行']
- ['start/beginner.md', '始め方', 'プログラミング初心者向け']
- ['start/programmer.md', '始め方', 'プログラミング経験者向け']
- ['start/fptomok.md', '始め方', '関数型言語経験者向け']
- ['tutorial/part01.md', 'チュートリアル', '第1章 はじめよう']
- ['tutorial/part02.md', 'チュートリアル', '第2章 基本的な構文と型']
- ['tutorial/part03.md', 'チュートリアル', '第3章 リストとタプル']
- ['lang/basic.md', '言語', '基本事項']
- ['lang/statement.md', '言語', '文']
- ['lang/type.md', '言語', '型とリテラル']
- ['lang/expression.md', '言語', '式']
- ['lang/pattern.md', '言語', 'パターン']
- ['lang/dotnet.md', '言語', '.NET関連の式']
- ['library/corelib.md', 'ライブラリ', 'コアライブラリ']
- ['library/list.md', 'ライブラリ', 'リストライブラリ']
- ['library/print.md', 'ライブラリ', '表示関数ライブラリ']
- ['library/graphics.md', 'ライブラリ', 'グラフィックスライブラリ']
- ['sample.md', 'サンプル']
